-- Import data for module_mapping
-- Total rows: 6

INSERT INTO module_mapping (id, course, module_id, module_name, keywords, description, display_order, created_at) VALUES (1, 'fitter', 'safety', 'Safety and First Aid', '{"safety","first aid","ppe","hazard","accident"}', 'Workshop safety, personal protective equipment, and first aid procedures', 1, '2026-02-28T14:29:22.108Z');
INSERT INTO module_mapping (id, course, module_id, module_name, keywords, description, display_order, created_at) VALUES (2, 'fitter', 'tools', 'Hand Tools and Measuring Instruments', '{"tools","measuring","instruments","vernier","micrometer"}', 'Hand tools, measuring instruments, and their proper usage', 2, '2026-02-28T14:29:22.155Z');
INSERT INTO module_mapping (id, course, module_id, module_name, keywords, description, display_order, created_at) VALUES (3, 'fitter', 'fitting', 'Fitting Operations', '{"fitting","filing","sawing","drilling","tapping"}', 'Basic fitting operations including filing, sawing, drilling, and threading', 3, '2026-02-28T14:29:22.200Z');
INSERT INTO module_mapping (id, course, module_id, module_name, keywords, description, display_order, created_at) VALUES (4, 'electrician', 'safety', 'Electrical Safety', '{"safety","electrical","shock","earthing","protection"}', 'Electrical safety practices, shock prevention, and protective measures', 1, '2026-02-28T14:29:22.250Z');
INSERT INTO module_mapping (id, course, module_id, module_name, keywords, description, display_order, created_at) VALUES (5, 'electrician', 'basics', 'Electrical Fundamentals', '{"voltage","current","resistance","ohm","circuit"}', 'Basic electrical concepts, Ohms law, and circuit theory', 2, '2026-02-28T14:29:22.298Z');
INSERT INTO module_mapping (id, course, module_id, module_name, keywords, description, display_order, created_at) VALUES (6, 'electrician', 'wiring', 'Electrical Wiring', '{"wiring","installation","conduit","cable","connection"}', 'Electrical wiring methods, installation practices, and connections', 3, '2026-02-28T14:29:22.349Z');
